env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
parserOptions:
  ecmaFeatures:
    jsx: false
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - jsx
  - js
rules: {}
